### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Luro02** [sile/hls_m3u8#18]
As you (@sile) might have realized, I am starting to get invested with this crate. The primary reason for this is, that you have the only usable `hls_m3u8` parser and I don't want to reinvent the wheel by creating my own.

Instead of just flooding you with random PRs, I want to give you some kind of information, of what I plan to do in the future;

- [ ] Better error messages (currently most of the library uses `Error::custom` or `Error::invalid_input`)
- [ ] A more relaxed parser (there are some things like control characters, that could simply be removed from the input, instead of returning an error)
- [ ] add a lot more tests
- [x] rework `Attributes`
- [ ] `rustfmt.toml`
- [ ] Reduce the amount of code duplication by using `derive_builder` and `getset` (getset needs some updates to be useful)
- [ ] Improve the user API. For example, easy switching between bitrates, fetching chunks and automatically decrypting them (would be behind feature flags).
- [ ] `no_std`?

I don't know if you trust me enough, but it'd be nice if you could allow me to merge PRs in this repository, so I don't have to wait on your review :)
Also, please wait with bumping the version of this crate, until a significant amount of changes have been done (there are [some crates](https://crates.io/crates/hls_m3u8/reverse_dependencies), who depend on this one).

**Comment by sile** [comment]
Thank you for sharing your plan. It seems really good.

> I don't know if you trust me enough, but it'd be nice if you could allow me to merge PRs in this repository, so I don't have to wait on your review :)

I'm sorry that I don't have enough time to review your PRs because I'm very busy this month.
I added you to collaborators, so feel free to merge your PR :)

**Comment by Luro02** [comment]
I split this in several issues, for better tracking.
